version: '3.7'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app/backend
      - static:/static
    # environment:
    #   - DJANGO_SETTINGS_MODULE=book_club.settings.development

  frontend:
    build:
      context: ./frontend
    volumes:
      - frontend:/app/build
    env_file:
      - ./frontend/.env
  
  nginx:
    build:
      context: ./nginx
    volumes:
      - static:/static
      - frontend:/var/www/frontend
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend


volumes:
  static:
  frontend: