# Generated by Django 5.0.6 on 2024-06-17 23:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("note", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
