# Generated by Django 5.0.6 on 2024-06-17 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("note", "0002_alter_note_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
