# Generated by Django 5.0.6 on 2024-06-18 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("note", "0003_note_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="updated_at",
        ),
    ]
