# Generated by Django 5.0.6 on 2024-06-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_book_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
