# Generated by Django 5.0.6 on 2024-06-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_alter_book_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="summary",
            field=models.TextField(null=True),
        ),
    ]
