# Generated by Django 5.0.6 on 2024-06-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_book_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="link",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
